# Configuration: https://gohugo.io/getting-started/configuration/
# Theme: https://themes.gohugo.io/hugo-book/

# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-157613383-1"

baseURL = "https://avito-tech.github.io/avito-android"
title = "Avito Android"
# TODO: use english as default
languageCode = "ru-ru"
DefaultContentLanguage = "ru"
theme = "book"
# WARNING: publishDir outside the project breaks i18n
publishDir = "public"

# Disable needless kinds (https://gohugo.io/templates/section-templates/#page-kinds):
# - We use explicit menu instead of section tree
disableKinds = ["section"]

[markup.tableOfContents]
# First level is used only as a page title
startLevel = 2
endLevel = 4

[params]
BookMenuBundle = "/menu"
BookRepo = "https://github.com/avito-tech/avito-android"
BookEditPath = "tree/develop/docs/content"
BookSearch = true
