# Configuration: https://gohugo.io/getting-started/configuration/
# Theme: https://themes.gohugo.io/hugo-book/

# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-157613383-1"

baseURL = "https://avito-tech.github.io/avito-android"
title = "Avito Android"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "book"
# WARNING: publishDir outside the project breaks i18n
publishDir = "public"

[markup.tableOfContents]
# First level is used only as a page title
startLevel = 2
endLevel = 4

[params]
BookMenuBundle = "/menu"
BookRepo = "https://github.com/avito-tech/avito-android"
BookEditPath = "tree/develop/docs/content"
BookSearch = true

# Portable links let you write markdown links without {{< relref >}} shortcode
# Examples: https://github.com/bep/portable-hugo-links/
# Reasons to disabling:
#   - Don't fail in case of missing page
# TODO: Find a workaround and enable
BookPortableLinks = false
